package com.hackathon.sales.dataobject;

public class PasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.id
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.encript_password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    private String encriptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.user_id
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.id
     *
     * @return the value of password.id
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.id
     *
     * @param id the value for password.id
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.encript_password
     *
     * @return the value of password.encript_password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    public String getEncriptPassword() {
        return encriptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.encript_password
     *
     * @param encriptPassword the value for password.encript_password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    public void setEncriptPassword(String encriptPassword) {
        this.encriptPassword = encriptPassword == null ? null : encriptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.user_id
     *
     * @return the value of password.user_id
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column password.user_id
     *
     * @param userId the value for password.user_id
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}