package com.hackathon.sales.dao;

import com.hackathon.sales.dataobject.PasswordDO;

public interface PasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int insert(PasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int insertSelective(PasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    PasswordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int updateByPrimaryKeySelective(PasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int updateByPrimaryKey(PasswordDO record);
}