package com.hackathon.sales.dao;

import com.hackathon.sales.dataobject.PasswordDO;
import com.hackathon.sales.dataobject.UserDO;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int insertSelective(UserDO record);
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Apr 12 21:15:56 CST 2021
     */
    int updateByPrimaryKey(UserDO record);
}